### ISSUE TITLE
block selection does not work as it should

### ISSUE THREAD

**Issue by diznover** [VenomCodeDev/JumpVaderMod#1]
well, it works, but only with three blocks, I'm not good at programming, but can you make it so that you can choose any block? Probably after Blocks. it can choose a word from the config, and I'm even ready to write names in uppercase, just wright in the config that to select a block, its name must be written with caps, as well as the selected block is not displayed in the inventory, it's still orange glass.
`{
        return switch (JumpVaderMod.getConfig().getAlternativeBlock()) {
            case "tinted_glass" -> Blocks.TINTED_GLASS;
            case "white_wool" -> Blocks.WHITE_WOOL;
            default -> Blocks.ORANGE_STAINED_GLASS;
        };
    }`

**Comment by AuxAtlas** [comment]
The solution currently implemented is a temporary one I rushed together in reponse to another's request to use Tinted Glass as the block instead of orange. Once I get back home in a few days, ill look into allowing any block to be chosen.
As for the orange glass in inventory instead of the selected block, that is indeed unintended but will also have to wait until im home to be fixed. Thanks for the report! Ill get to this asap.

**Comment by diznover** [comment]
Thank you for continuing to develop the mod, I hope you will be able to update it soon!

**Comment by AuxAtlas** [comment]
I am currently looking into how to do this. Unlike something like Spigot, Fabric doesnt have a built-in config system so in order to let the user select "any" block, I would have to write it myself which could take awhile. Im looking into making a separate library to handle this for me, but it will take some time. For now though, ill try to remember allow the selection of the 3/4 presets to work as it should. Including fixing the hand always showing orange glass. This will definitely have to wait until late tonight though unfortunately. Ill update this issue with more info when I get some.

**Comment by diznover** [comment]
To implement the config function, you can use this lib [cloth-config](https://modrinth.com/mod/cloth-config/versions)

**Comment by AuxAtlas** [comment]
Unfortunately, Cloth-Config's developer strongly asks to not have it be used in server mods. As stated [here](https://shedaniel.gitbook.io/cloth-config/setup-cloth-config/cloth-config-fabric)

**Comment by diznover** [comment]
hmm... [completeconfig](https://gitlab.com/Lortseam/completeconfig/-/wikis/home) is something like a fork of cloth config, but maybe it will be more acceptable for the server side, I didn't find any information about it in the wiki.

**Comment by AuxAtlas** [comment]
Finally fixed... almost a year later. To be fair this project was abandoned for a long period of time as I didn't plan to continue it until recently.

Regardless, fixed in latest version v1.0.3
