### ISSUE TITLE
Warp down twice when crouching

### ISSUE THREAD

**Issue by TheMasterBlaster** [VenomCodeDev/JumpVaderMod#4]
JumpVaders will move you down when pressing crouch and again when releasing crouch. It would be nice if there was a config to only allow moving downward when crouch was pressed.

**Comment by AuxAtlas** [comment]
Attempted to fix this with latest commit 2bccfd9 . This would be [JumpVaderMod v1.0.8+mc1.20.1](https://modrinth.com/mod/jumpvader/version/1.0.8+1.20.1). Please try it and let me know when you get a chance. I did all of this on mobile with ChromeRemoteDesktop since I dont have computer access for a few days (lol) so I have no way to test the changes ive done. Please feel free to report back here if it worked or not so that I know. Thanks!

**Comment by TheMasterBlaster** [comment]
Using build #12: Commit [2bccfd9] / version 1.0.8. Seems like nothing has really changed. The issue is exactly the same from my testing.

**Comment by AuxAtlas** [comment]
This might have to wait until i get home on sunday night. I do apologize! With such a small number of users, I dont get many issue reports, which makes these bugs last way longer than they should. I will get back to you on Sunday or early Monday. Thanks!

**Comment by AuxAtlas** [comment]
> Using build #12: Commit [2bccfd9] / version 1.0.8. Seems like nothing has really changed. The issue is exactly the same from my testing.

I forgot, is ServerAPI included inside JumpVaders, or did you download it separately? If you downloaded it seperately it might help to update ServerAPI aswell.

**Comment by TheMasterBlaster** [comment]
I updated the ServerAPI mod that's embedded inside JumpVaders to version v1.0.7 and pressing crouch will cause you to warp down, while releasing crouch does nothing. so it seems like that does fix the double warping bug.

**Comment by AuxAtlas** [comment]
Perfect! Thats one down then. Ill just have to update the embedded version. Thanks!

**Comment by AuxAtlas** [comment]
Updated the included ServerAPI version to latest in [v1.0.9+mc1.20.1](https://modrinth.com/mod/jumpvader/version/1.0.9+1.20.1) . This should resolve the bug. Thanks!
